version: '3.7'

services:
    webserver:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-webserver
        expose:
            - "80"
            - "443"
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ../:/application:cached
        environment:
            - VIRTUAL_HOST=${HOST_NAME}
            - VIRTUAL_PORT=80
        links:
            - application
        restart: unless-stopped
        networks:
            - application-network
    application:
        image: mace015/laravel-docker-application:latest
        container_name: ${PROJECT_NAME}-app
        volumes:
            - ../:/application:cached
        restart: unless-stopped
        networks:
            - application-network
    workspace:
        image: mace015/laravel-docker-workspace:latest
        container_name: ${PROJECT_NAME}-workspace
        volumes:
            - ../:/application:cached
        restart: unless-stopped
        networks:
            - application-network

networks:
    application-network:
        external:
            name: ${PROJECT_NAME}-network
